spring.application.name=webproject
server.port=8080

# DataSource
spring.datasource.url=jdbc:h2:file:./data/exemplo
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=admin

# H2 Console
spring.h2.console.enabled=true
