spring.application.name=DeskGo

# DataSource
spring.datasource.url=jdbc:h2:file:./data/deskgo
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=password

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Permite acesso ao console H2 de outros computadores na rede
spring.h2.console.settings.web-allow-others=true

# Permite que o Spring Boot reconheça corretamente os cabeçalhos X-Forwarded-* quando o aplicativo estiver atrás de um proxy reverso.
server.forward-headers-strategy=framework