spring.application.name=DeskGo
server.port=8080
server.address=0.0.0.0
server.forward-headers-strategy=framework

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.web.locale=pt_BR
spring.web.locale-resolver=fixed

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true
